### ISSUE TITLE
使用 tab 而不是 switch 来控制 JE/BE 切换

### ISSUE THREAD

**Issue by Dianliang233** [Teahouse-Studios/mcwzh-meme-web-builder#1]
使用 tab 而不是 switch 来控制 JE/BE 切换，更美观，也更方便。

**Comment by XxLittleCxX** [comment]
See https://github.com/Teahouse-Studios/mcwzh-meme-web-builder/commit/136e7fa8c3580fe1c3212a8cac52286504227079, https://github.com/Teahouse-Studios/mcwzh-meme-web-builder/commit/c5b0ba2949cd86854c29ef554d773d065b3c18fb
