### ISSUE TITLE
显示错误500

### ISSUE THREAD

**Issue by xiaozhu2007** [Teahouse-Studios/mcwzh-meme-web-builder#11]
**注意：这里是Web Builder的仓库，如果和资源包内容有关，强烈建议您前往 https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack 进行反馈。**

## 简述错误
请简明扼要地描述漏洞。

## 重现方法
复现漏洞的步骤：

1. 前往“...”
2. 点击“...”
3. 滑动至“...”
4. 查看错误

## 提交截图
截图能更好的帮助我们解决问题。

## 请选择完成以下信息
浏览器：
系统：
设备：OPPO

## 其他内容
添加更多关于漏洞的来龙去脉。
尝试1.12.2
显示500

**Comment by lakejason0** [comment]
Duplicate of #8
