### ISSUE TITLE
UI建议

### ISSUE THREAD

**Issue by XxLittleCxX** [Teahouse-Studios/mcwzh-meme-web-builder#17]
- [x] 在上面加一句类似于“我们一直在更新，请保持关注”之类的话可能会好一些
- [x] MCBBS/GitHub/唱片包的链接能搞得明白点吗
- [x] 建议附加内容默认全选保证体验，毕竟都说了不会选直接提交构建选项

from @SkyEye-FAST

**Comment by XxLittleCxX** [comment]
https://github.com/Teahouse-Studios/mcwzh-meme-web-builder/commit/d9daa36d21d0822e74906f938153e01218f7031b

**Comment by XxLittleCxX** [comment]
先撤回上述更改，原因：
![image](https://user-images.githubusercontent.com/26459759/95682430-c727fd80-0c17-11eb-8b91-a6cef89a497e.png)

不知道应该在网页手动指定部分内容，还是后端维护一份相互不兼容模块的列表，征询意见 @Dianliang233

**Comment by Dianliang233** [comment]
> 先撤回上述更改，原因：
> ![image](https://user-images.githubusercontent.com/26459759/95682430-c727fd80-0c17-11eb-8b91-a6cef89a497e.png)
> 
> 不知道应该在网页手动指定部分内容，还是后端维护一份相互不兼容模块的列表，征询意见 @Dianliang233

在后端拉清单。

**Comment by Dianliang233** [comment]
第一句话已添加到滚动提示
