### ISSUE TITLE
基岩版旧版支持说明

### ISSUE THREAD

**Issue by SkyEye-FAST** [Teahouse-Studios/mcwzh-meme-web-builder#204]
请在基岩版构建页面添加如下说明：

> 我们默认您使用的是最新版本的基岩版Minecraft。详情请见GitHub仓库的README.md。

同时“使用兼容选项”下的说明也请在最后增加“详见README.md”的字样。

“README.md”请直接链接到GitHub的页面。

**Comment by XxLittleCxX** [comment]
> 同时“使用兼容选项”下的说明也请在最后增加“详见README.md”的字样。

这个加链接不方便的, 先加个文字吧
