### ISSUE TITLE
构建基岩版资源包失败

### ISSUE THREAD

**Issue by RxinnotRstar** [Teahouse-Studios/mcwzh-meme-web-builder#206]
点击基岩版
随意搭配，不搭配也行
点击构建
提示构建失败
错误原因是network error
但是构建Java版是成功的
![图片](https://user-images.githubusercontent.com/56676566/127762107-4a6cecb2-9ae8-415f-890f-e58d863ef8c1.png)

**Comment by Dianliang233** [comment]
可以复现

**Comment by Dianliang233** [comment]
请求被 CORS 拦了，应该是内部错误

**Comment by XxLittleCxX** [comment]
已修复 `memepack-builder`没有更新
