### ISSUE TITLE
推荐在网站上添加资源文件最后一次更新的时间

### ISSUE THREAD

**Issue by RxinnotRstar** [Teahouse-Studios/mcwzh-meme-web-builder#207]
![图片](https://user-images.githubusercontent.com/56676566/128596037-7cf54178-440e-42ac-9584-feac932623d8.png)
如图，可以在这里加上一个当前版本的语言文件最后一次更新的时间（可以放具体的时间，也可以放x天前）
![图片](https://user-images.githubusercontent.com/56676566/128596103-06c1871e-d55f-41ce-918e-833dc4324e1c.png)

**Comment by lakejason0** [comment]
不知道后端实现是怎么实现的，但是这个东西应该是在后端的时候返回回来的就是（思考）

**Comment by lakejason0** [comment]
等相关人员回来看看

**Comment by XxLittleCxX** [comment]
https://github.com/Teahouse-Studios/mcwzh-meme-web-builder-server/commit/c12ba306c281d15212a1d56b8168e6205d7935ce
https://github.com/Teahouse-Studios/mcwzh-meme-web-builder/commit/2f03d3102cc67322006ad4bb3a37cbb3afe61dae

**Comment by RxinnotRstar** [comment]
> 
> 
> [Teahouse-Studios/mcwzh-meme-web-builder-server@c12ba30](https://github.com/Teahouse-Studios/mcwzh-meme-web-builder-server/commit/c12ba306c281d15212a1d56b8168e6205d7935ce)
> [2f03d31](https://github.com/Teahouse-Studios/mcwzh-meme-web-builder/commit/2f03d3102cc67322006ad4bb3a37cbb3afe61dae)

![图片](https://user-images.githubusercontent.com/56676566/129352759-f146355d-db73-428b-bde8-2df15e856d60.png)

**Comment by XxLittleCxX** [comment]
这个时间现在是浏览器生成的 谁让你系统还是中文（

**Comment by XxLittleCxX** [comment]
手动去指定时间格式化的语言没啥必要

**Comment by RxinnotRstar** [comment]
补充一点，网页语言是“梗体中文”的时候推荐改为“最后不咕时间“
