### ISSUE TITLE
梗化在线构建的梗体中文语言选项的内容

### ISSUE THREAD

**Issue by RxinnotRstar** [Teahouse-Studios/mcwzh-meme-web-builder#210]
我发现网页中语言为梗体中文的时候，有一部分文字还不够梗体中文。以下是我修改的内容（含有修正和新点子）。

格式：

原文
→修改后的文字
→其它可选的修改后的文字
//注释（如果有）

正文：

SPGoding 是一位 Mojang 管理员、泥潭噫术家，代表作《大憨批》VSCode 插件。ta 热心的赠送了梗体中文 7 天的泥潭广告位。 
→SPGoding 是一位 Bugjang 管理员、泥潭噫术家，代表作《大憨批》VSCode 插件。ta 让梗体中文白嫖了 7 天泥潭广告位，背后的原因让人暖心。

Kakagou 是一位 MCBBS 艺术家。他热心的赠送了梗体中文 7 天的 MCBBS 广告位。
→Kakagou 是一位泥潭噫术家。他让梗体中文白嫖了 7 天泥潭广告位，背后的原因让人暖心。

游戏版本
→游戏版本（不是版本，是版本）

（与 western_meme_modules 不兼容）
→（与 western_meme_modules 内讧）
//类似的文字同理

梗体中文 · 懒人构建
→梗体中文 · 当场构建
→梗体中文 · 一键生草
→梗体中文 · 在线生草
→梗体中文 · 云 服 务

这些金主爸爸均未给予 Teahouse Studios 梗体中文团队真实金钱，亦未强迫 Teahouse Studios 梗体中文团队将其添加至赞助者列表——这只是 Teahouse Studios 梗体中文团队对他们的支持最诚挚的感谢。❤️
→这些金主爸爸均未给予 Teahouse Studios 梗体中文团队打钱，亦未强迫 Teahouse Studios 梗体中文团队将其添加至金主爸爸列表——这只是 Teahouse Studios 梗体中文团队对他们表示“这个可以有！“最诚挚的感谢。❤️

MCBBS 资料页
→MCSSB资料页

苏打baka 是一位 Bilibili UP 主。她向她的 35w+ 粉丝推荐了梗体中文。
→苏打baka 是一位破站 UP 主。她向她的 35w+ 粉丝推荐了梗体中文。

BILIBILI 主页
→小破站主页

让您可以在使用其他附加包时不目害。此选项会把梗体中文内容覆盖到简体中文，因此在设置中只需选择“简体中文”即可体验。详见README.md。
→让您可以在使用其他亮目害眼包时不目害。此选项会让梗体中文无情霸占简体中文的位置，因此在设置中只需选择“简体中文”即可体验。详见 阅读我.md。

最后更新时间：
→最后不咕时间：
→在这之后制作组就去饮靓靓的beer了：
→船新版本更新时间：
→出炉时间：
→最后一次正确的配置：

选择您需要的附加包后缀。
→选择您需要的附加包后缀。（其实可以自己改的。）

作者：
→始 作 俑 者 ：

没人看的服务条款
→真得有人会看这些服务条款吗？

没人看的隐私政策
→真得有人会看这些隐私政策吗？

**Comment by XxLittleCxX** [comment]
你怎么不直接pr（

**Comment by lakejason0** [comment]
你怎么不直接pr（

**Comment by RxinnotRstar** [comment]
> 
> 
> 你怎么不直接pr（

问就是实在不会（

**Comment by RxinnotRstar** [comment]
> 
> 
> 你怎么不直接pr（

问就是实在不会（

**Comment by RxinnotRstar** [comment]
> 
> 
> > 你怎么不直接pr（
> 
> ~~问就是实在不会（~~
> ~~而且含有多个可选项，就算我知道怎么改文件并pr我也无法直接pr~~

**Comment by RxinnotRstar** [comment]
> 
> 
> > > 你怎么不直接pr（
> > 
> > 
> > ~问就是实在不会（~
> > ~而且含有多个可选项，就算我知道怎么改文件并pr我也无法直接pr~
> > https://github.com/Teahouse-Studios/mcwzh-meme-web-builder/pull/212

**Comment by EternityXuNuo** [comment]
.link
