### ISSUE TITLE
无法构建

### ISSUE THREAD

**Issue by Nevodev** [Teahouse-Studios/mcwzh-meme-web-builder#223]
总是失败，Error: Request failed with status code 502
切换为python后无法下载，
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<RequestId>613E07EB4EA6A23538990D76</RequestId>
<HostId>frontend-wdljt.oss-cn-shanghai.aliyuncs.com</HostId>
<Key>meme-resourcepack.a24451a.mcpack</Key>
</Error>

**Comment by XxLittleCxX** [comment]
已修复

**Comment by Nevodev** [comment]
> 已修复

妈呀你们也太快了

**Comment by XxLittleCxX** [comment]
你只要不反馈ts，就没啥大问题

**Comment by XxLittleCxX** [comment]
ts构建现在堵的很，正在排查
