### ISSUE TITLE
构建失败

### ISSUE THREAD

**Issue by lava114514** [Teahouse-Studios/mcwzh-meme-web-builder#285]
**注意：这里是Web Builder的仓库，如果和资源包内容有关，强烈建议您前往 https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack 进行反馈。**

## 简述错误
网页显示
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<RequestId>61FF37868E97533038444639</RequestId>
<HostId>frontend-wdljt.oss-cn-shanghai.aliyuncs.com</HostId>
<Key>mcwzh-meme.0d65426.zip</Key>
</Error>

## 重现方法
复现漏洞的步骤：

1. 前往“...”
2. 点击“构建”
3. 点击 下载
4. 查看错误

## 提交截图
截图能更好的帮助我们解决问题。

## 请选择完成以下信息
浏览器：华为浏览器
系统：鸿蒙
设备：HUAWEI Mate 30 Pro 5G

## 其他内容
添加更多关于漏洞的来龙去脉。

**Comment by XxLittleCxX** [comment]
已修复
