### ISSUE TITLE
懒人构建网页最底下左边的三个按钮重定向到无法访问的网址

### ISSUE THREAD

**Issue by chinese-wzq** [Teahouse-Studios/mcwzh-meme-web-builder#302]
**注意：这里是Web Builder的仓库，如果和资源包内容有关，强烈建议您前往 https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack 进行反馈。**

## 简述错误
你家懒人构建网页最底下隐私策略服务条款打钱3个按钮都不能点，会重定向到https://teahou.se/，但提示无法处理此请求

## 重现方法
复现漏洞的步骤：清楚的不得了，还要什么步骤

## 提交截图
清楚的不得了，还要什么截图

## 请选择完成以下信息
浏览器：Google Chrome
系统：Windows 11
设备：联想拯救者Y7000 2019 PG0

## 其他内容
没啥好说的

**Comment by Dianliang233** [comment]
wont fix
