### ISSUE TITLE
梗体中文唱片包无法下载

### ISSUE THREAD

**Issue by Dream-yyk** [Teahouse-Studios/mcwzh-meme-web-builder#325]
**注意：这里是Web Builder的仓库，如果和资源包内容有关，强烈建议您前往 https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack 进行反馈。**

## 简述错误
所有版本的唱片包都无法下载

## 重现方法
点击唱片包按钮

## 提交截图
![屏幕截图 2022-04-25 080736](https://user-images.githubusercontent.com/72236930/165002446-1da9d082-4e6e-43ce-a347-bbd719548255.jpg)

## 请选择完成以下信息
浏览器：Microsoft Edge
               版本 100.0.1185.50 (正式版本) (64 位)
系统：Windows10 21H2 19044.1645
设备：Huawei Matebook D15

## 其他内容
添加更多关于漏洞的来龙去脉。

**Comment by XxLittleCxX** [comment]
阿里云cdn自动关了 我去发个工单问问

**Comment by XxLittleCxX** [comment]
已更新 稍后再试
