### ISSUE TITLE
在向服务器请求资源模块列表时发生了错误。

### ISSUE THREAD

**Issue by Ghyuav** [Teahouse-Studios/mcwzh-meme-web-builder#326]
**注意：这里是Web Builder的仓库，如果和资源包内容有关，强烈建议您前往 https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack 进行反馈。**

## 简述错误
前往 https://meme.teahouse.team/ 时提示：
错误
在向服务器请求资源模块列表时发生了错误。

## 重现方法
复现漏洞的步骤：

1. 前往“[...](https://meme.teahouse.team/)”

## 提交截图
![image](https://user-images.githubusercontent.com/89256344/167522511-7362ab39-d5a2-44af-a988-28ef46b11757.png)
![image](https://user-images.githubusercontent.com/89256344/167522831-5acc13dd-b41c-4018-8165-01b786cc1edb.png)

## 请选择完成以下信息
浏览器：Microsoft Edge | 101.0.1210.39 (正式版本) (64 位)
系统：Windows 10 企业版 21H2
设备：台式机

## 其他内容
添加更多关于漏洞的来龙去脉。

**Comment by XxLittleCxX** [comment]
修了（
