### ISSUE TITLE
无法在线构建

### ISSUE THREAD

**Issue by ABCDCreeper** [Teahouse-Studios/mcwzh-meme-web-builder#328]
**注意：这里是Web Builder的仓库，如果和资源包内容有关，强烈建议您前往 https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack 进行反馈。**

## 简述错误
请简明扼要地描述漏洞。
无法在线构建
## 重现方法
复现漏洞的步骤：

1. 前往“.在线构建
2.出现无法链接服务器错误（挂vpn也没有用）

## 提交截图
截图能更好的帮助我们解决问题。
![image](https://user-images.githubusercontent.com/43110903/170643474-4963cf0f-f03c-40c3-9c24-16f7f517668f.png)

## 请选择完成以下信息
浏览器：Edge
系统：win11
设备：thinkpad t14

## 其他内容
添加更多关于漏洞的来龙去脉。

**Comment by Dianliang233** [comment]
服务无异常，请检查网络环境
