### ISSUE TITLE
构建页面梗中翻译不完整

### ISSUE THREAD

**Issue by zhenlige** [Teahouse-Studios/mcwzh-meme-web-builder#331]
## 简述错误
苏打的介绍中“Bilibili”未替换为“破站”（对比秋夕）
~连构建页面都有梗中也是离谱~

## 重现方法
复现漏洞的步骤：

1. 构建页面语言切换为梗体中文
2. 查看错误

## 提交截图
<img width="894" alt="image" src="https://user-images.githubusercontent.com/38127204/175487939-80b715de-0fc8-4c62-829c-72f1444ca3c6.png">

**Comment by Dianliang233** [comment]
在新版已弃用
