### ISSUE TITLE
启动在线构建报错

### ISSUE THREAD

**Issue by MiaoSiyuan** [Teahouse-Studios/mcwzh-meme-web-builder#334]
## 简述错误
启动在线构建报错，重进也一样，报错信息：“在向服务器请求资源列表时发生了错误”，读取不出列表
## 重现方法
复现漏洞的步骤：
1.打开浏览器
2.打开在线构建 meme.teahouse.team

## 提交截图
![image](https://user-images.githubusercontent.com/102292833/180601322-4ab33f7a-bda5-41ca-bc8d-cf381356b4ee.png)

## 请选择完成以下信息
浏览器：Microsoft Edge
版本 103.0.1264.71 (正式版本) (64 位)
系统：
Windows 10 专业版
版本号：21H1
安装日期：‎2021/‎6/‎29
操作系统内部版本：19043.1826
体验：Windows Feature Experience Pack 120.2212.4180.0
设备：电脑

## 其他内容
下午还可以访问的，傍晚就不行了，尽快 Bug，谢谢

**Comment by Dianliang233** [comment]
此问题现已被修复。感谢汇报。
