### ISSUE TITLE
OMG

### ISSUE THREAD

**Issue by imfine2333** [Teahouse-Studios/mcwzh-meme-web-builder#335]
**注意：这里是Web Builder的仓库，如果和资源包内容有关，强烈建议您前往 https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack 进行反馈。**

## 简述错误
网页无法构建。

## 重现方法
复现漏洞的步骤：

1. 前往“在线构建”
2. 查看错误

## 提交截图
![屏幕截图(10)](https://user-images.githubusercontent.com/109073573/186297783-825f0486-607a-42df-9b19-93bea3bf6bf4.png)

## 请选择完成以下信息
浏览器：MS Edge 104
系统：Windows 11 Home
设备：2021 Alienware Aurora R12

## 其他内容
无。

**Comment by Dianliang233** [comment]
已修复，感谢回报
