### ISSUE TITLE
回复

### ISSUE THREAD

**Issue by ly040519** [Teahouse-Studios/mcwzh-meme-web-builder#56]
版本 1.16.3 fabric
mod，材质：
![1](https://user-images.githubusercontent.com/75530031/102003865-2accc500-3d46-11eb-897b-9713429998bd.png)
![magick](https://user-images.githubusercontent.com/75530031/102003869-2d2f1f00-3d46-11eb-9077-aa5d36ec79ab.png)

对于梗体中文材质：删除了草和太阳花还有painting中的图片
重新构建材质时发现的问题：mod支持选项中选择全部并不会加上optfine的翻译（以及**mod loaders）

**Comment by lakejason0** [comment]
请不要此repo回复。issue已被转移到[这里](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/issues/138)。
