### ISSUE TITLE
报告BUG

### ISSUE THREAD

**Issue by meowOmeow101** [Teahouse-Studios/mcwzh-meme-web-builder#6]
你好关于梗体中文的网站我遇到了一个问题
Error: Request failed with status code 500
每次点击提交构建选项的时候就是这样的
这是什么原因？

**Comment by Dianliang233** [comment]
运维来认罪了
刚刚服务器硬盘满了，在挂载新硬盘的时候把服务器炸了
在半小时的抢修后已经恢复了
