### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by HMIHemingway** [Teahouse-Studios/mcwzh-meme-web-builder#7]
整个音游模式，比如“土豆”是“616服务器”之类的

**Comment by lakejason0** [comment]
内容建议应当在[这里](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/issues)提出。
顺便，我们也非常喜欢音游梗，但是苦于位置我们并不能塞在很明显的地方。
