### ISSUE TITLE
Error: Request failed with status code 500

### ISSUE THREAD

**Issue by Sshiweb** [Teahouse-Studios/mcwzh-meme-web-builder#8]
**注意：这里是Web Builder的仓库，如果和资源包内容有关，强烈建议您前往 https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack 进行反馈。**

## 简述错误
请简明扼要地描述漏洞。

## 重现方法
复现漏洞的步骤：

旧版本构建

## 提交截图
截图能更好的帮助我们解决问题。

## 请选择完成以下信息
浏览器：
系统：
设备：

## 其他内容
添加更多关于漏洞的来龙去脉。

**Comment by XxLittleCxX** [comment]
请提供更多内容，如：构建参数或截图

**Comment by lakejason0** [comment]
问题应该已经修复了。

**Comment by lakejason0** [comment]
不对怎么还没有@Dianliang233 出来挨打

**Comment by lakejason0** [comment]
仓库中的代码已经修复了……
但是不知为何服务器依然有问题。

**Comment by XxLittleCxX** [comment]
已修复
