### ISSUE TITLE
炸了（无法获取资源包列表）

### ISSUE THREAD

**Issue by lakejason0** [Teahouse-Studios/mcwzh-meme-web-builder#91]
**注意：这里是Web Builder的仓库，如果和资源包内容有关，强烈建议您前往 https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack 进行反馈。**

## 简述错误
访问[https://dl.meme.teahou.se]会无法获取资源列表。

## 重现方法
复现漏洞的步骤：

1. 前往“[https://dl.meme.teahou.se]”
2. 炸

## 提交截图
![image](https://user-images.githubusercontent.com/36039861/107154051-c75cbd80-69ab-11eb-9be0-17f3774f429f.png)

**Comment by XxLittleCxX** [comment]
fixed
